### ISSUE TITLE
What if mod_wsgi was installed prior to this package?

### ISSUE THREAD

**Issue by sirfz** [GrahamDumpleton/mod_wsgi-httpd#1]
Haven't actually tried this yet but I was wondering if there's any side effects if `mod_wsgi` was already installed before `mod_wsgi-httpd`?

**Comment by GrahamDumpleton** [comment]
The mod_wsgi-httpd package doesn't touch your existing system Apache installation, so if you already have separately compiled mod_wsgi from source code into your system Apache installation, it will not be affected.

This mod_wsgi-httpd package installs a copy of Apache in a special directory inside of the Python installation or virtual environment. This Apache is not readily runnable directly, you need to then also (re)install the pip installable mod_wsgi package for it to use this Apache. That will compile and install the mod_wsgi module into the same Python installation or virtual environment as Apache was installed using this package. You then use the mod_wsgi-express which was installed and it will use the Apache installed via this package and ignore your system Apache.

So, if you had already done a 'pip install mod_wsgi', it will keep using whatever Apache it was built against. If is only if you 'pip install -U mod_wsgi' to reinstall it that it will then use the Apache installed by mod_wsgi-httpd. So there is an ordering requirement, installing mod_wsgi-httpd will not change what an existing pip installable mod_wsgi is using.

Important is that you only need to bother with the mod_wsgi-httpd package if you don't have a system Apache which is complete with developer files, or if you want to use the latest Apache where system Apache is old.

**Comment by sirfz** [comment]
Alright great, thanks for the clarification and for the amazing work!
